### ISSUE TITLE
[1.17.1] This mod in a large pack causes the pack not to load.

### ISSUE THREAD

**Issue by ProsperCraft** [CodersLabs/Tougher-Glass-Forge#2]
I loaded with only this mod and it loads, but when added to TownCraft THREE it causes this-

https://gist.github.com/ProsperCraft/b71c1a2847f74a22b0dc00fedfb3afa5

Exception while loading data for manager elementalcraft:spell_properties: java.util.concurrent.CompletionException: java.lang.IllegalStateException

When removed, it loads again.

**Comment by Uraneptus** [comment]
Sorry saw that just now, gonna look into it later this day!

**Comment by Uraneptus** [comment]
[https://www.curseforge.com/minecraft/mc-mods/tougher-glass-forge/files/3591512](url) 
This version should fix the error you had, can't say for sure though since I couldn't reproduce the error.
If it still doesn't work pls report it again.
Do note tho, this version is for mc 1.18.1
